
ren    BPC_B335_Matplotlib_Quiz20_mission.ipynb         BPC_B435_Matplotlib_Quiz20_mission.ipynb                             
ren    BPC_B310_NumPy.ipynb							  	BPC_B410_NumPy.ipynb                                                 
ren    BPC_B311_NumPy.ipynb							  	BPC_B411_NumPy.ipynb                                                 
ren    BPC_B312_NumPy.ipynb							  	BPC_B412_NumPy.ipynb                                                 
ren    BPC_B312_NumPy-Copy1.ipynb					    BPC_B412_NumPy-Copy1.ipynb                                             
ren    BPC_B313_NumPy.ipynb							  	BPC_B413_NumPy.ipynb                                                 
ren    BPC_B315_NumPy.ipynb							  	BPC_B415_NumPy.ipynb                                                 
ren    BPC_B316_NumPy.ipynb							  	BPC_B416_NumPy.ipynb                                                 
ren    BPC_B320_Pandas.ipynb						    BPC_B420_Pandas.ipynb                                                  
ren    BPC_B321_Pandas.ipynb						    BPC_B421_Pandas.ipynb                                                  
ren    BPC_B322_Pandas.ipynb						    BPC_B422_Pandas.ipynb                                                  
ren    BPC_B322_Pandas_ver2.ipynb					    BPC_B422_Pandas_ver2.ipynb                                             
ren    BPC_B323_Pandas.ipynb						    BPC_B423_Pandas.ipynb                                                  
ren    BPC_B323_Pandas_ver2.ipynb					    BPC_B423_Pandas_ver2.ipynb                                             
ren    BPC_B324_Pandas.ipynb						    BPC_B424_Pandas.ipynb                                                  
ren    BPC_B324_Pandas_ver2.ipynb					    BPC_B424_Pandas_ver2.ipynb                                             
ren    BPC_B325_Pandas.ipynb						    BPC_B425_Pandas.ipynb                                                  
ren    BPC_B326_Pandas.ipynb						    BPC_B426_Pandas.ipynb                                                  
ren    BPC_B329_Pandas_10M_00.ipynb					  	BPC_B429_Pandas_10M_00.ipynb                                         
ren    BPC_B329_Pandas_10M_01.ipynb					  	BPC_B429_Pandas_10M_01.ipynb                                         
ren    BPC_B329_Pandas_10M_02.ipynb					  	BPC_B429_Pandas_10M_02.ipynb                                         
ren    BPC_B329_Pandas_10M_03.ipynb					  	BPC_B429_Pandas_10M_03.ipynb                                         
ren    BPC_B330_Matplotlib.ipynb					    BPC_B430_Matplotlib.ipynb                                              
ren    BPC_B331_Matplotlib_Basic_Chart.ipynb		    BPC_B431_Matplotlib_Basic_Chart.ipynb                                  
ren    BPC_B332_Matplotlib_Color_Style.ipynb		    BPC_B432_Matplotlib_Color_Style.ipynb                                  
ren    BPC_B333_Matplotlib_Annotattion.ipynb		    BPC_B433_Matplotlib_Annotattion.ipynb                                  
ren    BPC_B334_Matplotlib_Seaborn.ipynb			    BPC_B434_Matplotlib_Seaborn.ipynb                                      
ren    BPC_B334_Matplotlib_Seaborn_ver2.ipynb		    BPC_B434_Matplotlib_Seaborn_ver2.ipynb                                 
ren    BPC_B335_Matplotlib_Quiz.ipynb				    BPC_B435_Matplotlib_Quiz.ipynb                                         
ren    BPC_B335_Matplotlib_Quiz_mission.ipynb		    BPC_B435_Matplotlib_Quiz_mission.ipynb                                 
ren    BPC_B335_Matplotlib_Quiz20.ipynb				  	BPC_B435_Matplotlib_Quiz20.ipynb                                     

